Sprint 6: исправлены старые ошибки, сделаны новые задания
AndreySanzharov/java-kanban pull request #1
Opened 2024-07-23 15:26 UTC by AndreySanzharov

2024-07-23 19:18 UTC, sergeymamonov commented
> В ходе тестирования выяснилось, что тесты работают не изолированно, а один влияет на другой. Если запускать тесты по одному, то они проходят, но если запускать уже набор тестов, то они будут мешать друг другу. Посмотрел в интернете, как их изолировать друг от друга, но не нашел ничего полезного. Чтобы GitHub Actions принял пул реквест (видимо, он запускает тесты не по одному), я "подогнал" тесты. Логически все верно, но проблема с изоляцией тестов не решилась.

Обсуждали этот вопрос с наставником?

2024-07-23 19:28 UTC, sergeymamonov requested changes
Коммитом нужно давать осмысленное название. Не нужно делать несколько коммитов с одним и тем же названием.

2024-07-23 19:28 UTC, sergeymamonov commented on src/javakanban/elements/Epic.java
> +    public List<Subtask> subtaskList = new ArrayList<>();
Почему паблик? Лучше приватный модификатор выбрать и доступ через геттер из других классов.

2024-07-23 19:28 UTC, sergeymamonov commented on src/javakanban/elements/Task.java
>      String name;
Пропущены модификаторы доступа.

2024-07-23 19:28 UTC, sergeymamonov commented on src/javakanban/managers/InMemoryHistoryManager.java
> +    private void linklast(Task task) {
camelCase

2024-07-23 19:28 UTC, sergeymamonov commented on src/javakanban/managers/InMemoryHistoryManager.java
> +            tail = newNode;
Общую часть можно выделить за рамки оператора if/else.

2024-07-23 19:28 UTC, sergeymamonov commented on src/javakanban/managers/InMemoryHistoryManager.java
> +    private List<Task> getTasks() {
Обычно в классе располагаются сначала все публичные методы, а потом приватные.

2024-07-23 19:28 UTC, sergeymamonov commented on src/javakanban/managers/Managers.java
> +    public static TaskManager getDefault() {
Этот метод где-то вызывается? А как вы создаете InMemoryTaskManager в приложении?

2024-07-23 20:04 UTC, AndreySanzharov commented on src/javakanban/managers/Managers.java
> +    public static TaskManager getDefault() {
На данный момент просто негде вызывать этот метод. В InMemoryHistoryManager это не требуется. Для приличия добавил вызов в Main.  Сам метод был сделан по заданию прошлого спринта.

2024-07-23 20:17 UTC, AndreySanzharov commented
> > В ходе тестирования выяснилось, что тесты работают не изолированно, а один влияет на другой. Если запускать тесты по одному, то они проходят, но если запускать уже набор тестов, то они будут мешать друг другу. Посмотрел в интернете, как их изолировать друг от друга, но не нашел ничего полезного. Чтобы GitHub Actions принял пул реквест (видимо, он запускает тесты не по одному), я "подогнал" тесты. Логически все верно, но проблема с изоляцией тестов не решилась.
> 
> Обсуждали этот вопрос с наставником?
Еще не обсуждал

2024-07-24 20:12 UTC, sergeymamonov approved these changes

2024-07-24 20:12 UTC, sergeymamonov commented on src/javakanban/elements/Task.java
> +    public String name;
Поля лучше сделать приватными и сделать для них геттеры и сеттеры при необходимости.

2024-07-24 20:12 UTC, sergeymamonov commented on src/javakanban/managers/InMemoryHistoryManager.java
> +            tail = newNode;
tail = newNode; и в ифе, и в элсе, значит можно вынести за пределы этого оператора.

2024-07-24 20:12 UTC, sergeymamonov commented on test/ExeptionsTest.java
> +public class ExeptionsTest {
Здесь можно вызвать getDefault()

2024-07-24 20:12 UTC, sergeymamonov commented on test/HistoryManagerTest.java
> +    InMemoryTaskManager inMemoryTaskManager = new InMemoryTaskManager();
Здесь можно вызвать getDefault()

2024-07-24 20:12 UTC, sergeymamonov commented on test/TaskManagerTest.java
> +    InMemoryTaskManager inMemoryTaskManager = new InMemoryTaskManager();
Здесь можно вызвать getDefault()

2024-08-05 14:30 UTC, merged