добавлено сохранение в файл и загрузка из  него
AndreySanzharov/java-kanban pull request #2
Opened 2024-08-07 12:24 UTC by AndreySanzharov

2024-08-09 03:35 UTC, sergeymamonov requested changes

2024-08-09 03:35 UTC, sergeymamonov commented on src/javakanban/managers/FileBackedTaskManager.java
> +        File file = new File("src/javakanban/save/load.csv");
Не очень хорошее место для сохранения файла, так как папка src это папка с кодом. И в этой папке не нужно хранить файлы с данными, которые генерирует сервис. Но в учебных целях можете оставить.

2024-08-09 03:35 UTC, sergeymamonov commented on src/javakanban/managers/FileBackedTaskManager.java
> +                if (type.equals("TASK")) {
Метод equals необходимо вызывать у константы или у значения, которое гарантированно не равно null. Потому что если значение, у которого вызывается метод equals будет равно null, то получим NPE. Проверьте в остальных случаях, как вызывается метод equals.

2024-08-09 03:35 UTC, sergeymamonov commented on src/javakanban/managers/FileBackedTaskManager.java
> +            System.out.println(e.getMessage());
Из ТЗ:
Исключения вида IOException нужно отлавливать внутри метода save и выкидывать собственное непроверяемое исключение ManagerSaveException.

2024-08-09 03:35 UTC, sergeymamonov commented on src/javakanban/managers/InMemoryTaskManager.java
> +    public static Map<Integer, Task> taskMap = new HashMap<>();
Зачем добавлен модификатор static?

2024-08-09 03:35 UTC, sergeymamonov commented on src/javakanban/managers/FileBackedTaskManager.java
> +import javakanban.elements.*;
Не используйте импорт через звездочку.

2024-08-09 10:02 UTC, AndreySanzharov commented on src/javakanban/managers/FileBackedTaskManager.java
> +        File file = new File("src/javakanban/save/load.csv");
Да, место для файлов было выбрано только из соображений учебного удобства.

2024-08-09 10:47 UTC, AndreySanzharov commented on src/javakanban/managers/InMemoryTaskManager.java
> +    public static Map<Integer, Task> taskMap = new HashMap<>();
Модификатор static тут нужен, чтобы я мог обращаться к этим мапам в классе FileBackedTaskManager для работы с ними. Создание экземпляра класса через getDefault дает мне доступ к методам InMemoryTaskManager, но не к полям (а мне нужны именно эти мапы). А поскольку эти поля не должны быть уникальными для каждого класса, я могу сделать их статическими и обращаться к ним, где это необходимо.

2024-08-10 05:29 UTC, sergeymamonov commented on src/javakanban/managers/FileBackedTaskManager.java
> +    public static void main(String[] args) throws IOException {
Не нужно возвращать IOException в сигнатуре методе. В задании сказано, что нужно перехватывать IOException и возвращать свою ошибку, которая унаследована от RuntimeException, и в сигнатуре не будет никаких исключений.

2024-08-10 05:29 UTC, sergeymamonov commented on src/javakanban/managers/InMemoryTaskManager.java
> +    public static Map<Integer, Task> taskMap = new HashMap<>();
Не нужно так рассуждать. Нужно создавать экземпляры классов, передавать куда нужно эти экземпляры и работать через геттеры для обращения к нужным полям этих экземпляров классов.

2024-08-10 05:29 UTC, sergeymamonov approved these changes

2024-08-20 10:13 UTC, merged