Sprint 8 solution time and duration
AndreySanzharov/java-kanban pull request #3
Opened 2024-08-20 21:25 UTC by AndreySanzharov

2024-08-21 21:03 UTC, sergeymamonov requested changes
ManagerSaveException - оставьте только те конструкторы, которые действительно используются.

2024-08-21 21:03 UTC, sergeymamonov commented on src/javakanban/elements/Task.java
> +            return startTime.plus(duration);
Если startTime будет равно null, а duration != null, то здесь будет NPE.

2024-08-21 21:03 UTC, sergeymamonov commented on src/javakanban/interfaces/TaskManager.java
> +    public TreeSet<Task> getPrioritizedTasks();
В интерфейсе все методы и так публичные.

2024-08-21 21:03 UTC, sergeymamonov commented on src/javakanban/managers/FileBackedTaskManager.java
> +        ;
Лишняя точка с запятой.

2024-08-21 21:03 UTC, sergeymamonov commented on src/javakanban/managers/InMemoryTaskManager.java
> +        TreeSet<Task> prioritizedTasks = new TreeSet<>(new Comparator<Task>() {
Можно вот так еще

comparing(Task::getStartTime).thenComparing(...)

На мой взгляд так более очевидно и наглядно.

2024-08-21 21:03 UTC, sergeymamonov commented on src/javakanban/managers/InMemoryTaskManager.java
> +        if (higher != null && newTask.getEndTime().isAfter(higher.getStartTime())) {
Можно сразу на написать return логическое выражение.

2024-08-21 21:03 UTC, sergeymamonov commented on test/EpicTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Не используйте импорт через *. Лучше отключить wildcard import https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcards-for-class

2024-08-21 21:03 UTC, sergeymamonov commented on test/ExeptionsTest.java
>      InMemoryTaskManager inMemoryTaskManager = new InMemoryTaskManager();
Я бы и в тестах полям давал модификатор доступа.

2024-08-22 11:07 UTC, AndreySanzharov commented on src/javakanban/elements/Task.java
> +            return startTime.plus(duration);
Заменю "и" на "или". Тогда будет выдавать нулл даже если только один параметр нулл

2024-08-22 11:14 UTC, AndreySanzharov commented on test/EpicTest.java
> +import static org.junit.jupiter.api.Assertions.*;
отключил, спасибо

2024-08-22 20:28 UTC, sergeymamonov approved these changes

2024-08-22 20:28 UTC, sergeymamonov commented on src/javakanban/elements/Task.java
> +                ", endTime= '" + getEndTime().format(FORMATTER) + '\'' +
getEndTime() может вернуть null. И поэтому здесь может быть NPE. Возвращая null нужно понимать, что можно сделать где-то NPE. Как вариант, проверять входные параметры в методе getEndTime(). И если какой-то важный параметр отсутствует кидать какую-то ошибку.

2024-08-22 20:28 UTC, sergeymamonov commented on test/InMemoryTaskManagerTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Исправить импорт.

2024-08-29 10:37 UTC, merged