Sprint 9 solution http api
AndreySanzharov/java-kanban pull request #5
Opened 2024-09-01 13:34 UTC by AndreySanzharov

2024-09-02 04:31 UTC, sergeymamonov requested changes
ManagerSaveException - оставить только используемые конструкторы.
Класс Task поле id не нужно его делать публичным, если уж и нужно обращаться из других классов к нему, то через геттер и сеттер.
В том же классе FORMATTER без модификатора доступа, так и задумывалось.

2024-09-02 04:31 UTC, sergeymamonov commented on out/production/java-kanban/javakanban/save/load.csv
> +id,type,name,status,description
Все файлы, которые нужны для запуска тестов, в папку test/resource. Каждый раз генерируемые файлы - такие в гитигнор нужно записать, чтобы они не попадали в коммиты.

2024-09-02 04:31 UTC, sergeymamonov commented on src/javakanban/managers/InMemoryTaskManager.java
>      HistoryManager inMemoryHistoryManager = Managers.getDefaultHistory();
Модификатор доступа. И для мап выше я бы поменял на приватный.

2024-09-02 04:31 UTC, sergeymamonov commented on src/javakanban/managers/InMemoryTaskManager.java
> +        List<Subtask> rez = epic.getSubtaskList();
return epic.getSubtaskList();

2024-09-02 04:31 UTC, sergeymamonov commented on src/server/handlers/BaseHttpHandler.java
> +    static TaskManager taskManager = Managers.getDefault();
Не нужно делать эти поля статическими. Это приватные поля тестового класса.

2024-09-02 04:31 UTC, sergeymamonov commented on src/server/handlers/PrioritizedHandler.java
> +        }
default

2024-09-02 04:31 UTC, sergeymamonov commented on src/server/handlers/PrioritizedHandler.java
> +        }
default

2024-09-03 19:40 UTC, sergeymamonov approved these changes

2024-09-03 19:40 UTC, sergeymamonov commented on src/javakanban/managers/InMemoryTaskManager.java
>      public static Map<Integer, Task> taskMap = new HashMap<>();
Лучше сделать приватными.

2024-09-03 19:40 UTC, sergeymamonov commented on src/server/handlers/BaseHttpHandler.java
> +    TaskManager taskManager = Managers.getDefault();
Модификатор доступа для полей класса.

2024-09-03 19:41 UTC, sergeymamonov approved these changes

2024-09-03 19:41 UTC, sergeymamonov commented on out/production/java-kanban/javakanban/save/load.csv
> +id,type,name,status,description
Поправить это замечание. Добавить генерируемые файлы в гитигнор.

2024-09-03 19:43 UTC, AndreySanzharov commented on out/production/java-kanban/javakanban/save/load.csv
> +id,type,name,status,description
уже добавил, в файле гитигнора можно увидеть /src/javakanban/save/

2024-11-28 16:59 UTC, merged